# Generated by Django 5.0.6 on 2024-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeFa', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.ManyToManyField(to='homeFa.technology'),
        ),
    ]
