# Generated by Django 5.0.6 on 2024-05-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='tittle',
            new_name='name',
        ),
    ]
