# Generated by Django 5.0.6 on 2024-05-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_aboutme_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='img/Technology')),
                ('name', models.CharField(max_length=25)),
                ('level', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='img/Tools')),
                ('name', models.CharField(max_length=25)),
                ('level', models.CharField(max_length=25)),
            ],
        ),
    ]
