# Generated by Django 5.0.6 on 2024-05-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_otherskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='img/Project')),
                ('tittle', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
