# Generated by Django 5.0.6 on 2024-05-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='message2',
            field=models.TextField(null=True),
        ),
    ]
