# Generated by Django 5.0.6 on 2024-05-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ticket_message2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='message2',
        ),
    ]
